Prototype implementation
reside-ic/porcelain pull request #1
Opened 2020-02-28 17:31 UTC by richfitz

This does really not do enough to be useful but it should serve as a starting point.

Things that I kept *out* of the MVP:

* Accept POST endpoints - we need to get ahead of the postBody filter and do some big surgery. this will affect endpoints that use queries too. Plumber in it's current form does not really allow binary uploads without some work.
* Translation support :grinning: 
* Logging
* Support for pulling up (and discarding) a real server we can throw queries at, like in hintr
* Swagger support and reporting back the schemas
* Build-time (rather than run time) matching of query args to function args (this will tie in with the first point and the swagger point)
* Make jsonvalidate an optional dependency
* Make it easy to enforce always checking schemas in tests

2020-03-02 16:23 UTC, r-ash requested changes
This looks great, I think will support many of the things we're doing in hintr already. A list below of the things in hintr from a look which might impact this

* POST endpoints - we've talked about and is coming in another PR
* GET - supported at the moment
* HEAD - should work for free as GET is working
* params in the path - in hintr we're not sending these as like `path?x=y` but as `path/<id>` or so - we've got a test showing that is working already
* to_json conversion - agree it should be tuneable, we should make a ticket for that
* zip - Content-Disposition and a specific serializer, we have the serializer (just the binary type) but this sets the filename for the download via the Content-Disposition header - perhaps we could extend the `pkgapi_returning_binary` to accept an arg for the filename? See https://github.com/mrc-ide/hintr/blob/master/R/endpoints.R#L491

2020-03-02 16:23 UTC, r-ash commented on R/endpoint.R
> +    ##' standardised response pbject that contains \code{status_code},
Small typo on `object`

2020-03-02 16:23 UTC, r-ash commented on R/endpoint.R
> +    ##' \code{content_type}, \code{body} (the serialised output as tun
`run` instead of `tun`?

2020-03-02 16:23 UTC, r-ash commented on tests/testthat/test-validation.R
> +test_that("allow missing schema", {
Is there a use case you have in mind for allowing a missing schema but having `validate = TRUE`?

2020-03-02 16:23 UTC, r-ash commented on R/returning.R
> +  status_code <- status_code
This line not needed?

2020-03-02 16:23 UTC, r-ash commented on R/returning.R
> +  status_code <- status_code
Same with this line?

2020-03-02 16:23 UTC, r-ash commented on R/error.R
> +    stop("All error details must be character or NULL", call. = FALSE)
It will be hard to debug should this error be thrown as the call stack isn't being returned - perhaps this is the kind of place you want to log that information though?

2020-03-02 16:23 UTC, r-ash commented on R/error.R
> +  detail <- vcapply(data, "[[", "error")
Should be `detail <- vcapply(data, "[[", "detail")` - we should probably test this in `test-error.R`.

2020-03-02 16:23 UTC, r-ash commented on docker/build
> +       --build-arg DETTL_VERSION=$PKG_VERSION \
`DETTL_VERSION`?

2020-03-02 16:23 UTC, r-ash commented on docker/Dockerfile
> +FROM rocker/r-ver:latest
The docker build exists as we will extend this as the base image in things like hintr?

2020-03-02 16:41 UTC, richfitz commented on tests/testthat/test-validation.R
> +test_that("allow missing schema", {
just making sure we don't get an error - `validate = TRUE` should read as "use whatever validation is provided" and `schema = NULL` should read as "match all schemas"

2020-03-02 16:42 UTC, richfitz commented on R/error.R
> +    stop("All error details must be character or NULL", call. = FALSE)
Logged as RESIDE-104

2020-03-02 16:44 UTC, richfitz commented on R/error.R
> +  detail <- vcapply(data, "[[", "error")
yes, this was badly broken. Nice catch - I've added a simple test too

2020-03-02 16:45 UTC, richfitz commented on docker/build
> +       --build-arg DETTL_VERSION=$PKG_VERSION \
Oops :upside_down_face:

2020-03-02 16:46 UTC, richfitz commented on docker/Dockerfile
> +FROM rocker/r-ver:latest
yeah, exactly. So the hintr image could build off of this and we'll centralise some of the scripts that we use to provision it etc

2020-03-02 16:46 UTC, richfitz commented on docker/Dockerfile
> +FROM rocker/r-ver:latest
I built this to debug a travis failure though, and just kept it in the package

2020-03-02 16:48 UTC, richfitz commented
> * POST endpoints - we've talked about and is coming in another PR

RESIDE-103

> * GET - supported at the moment
> * HEAD - should work for free as GET is working

Do we use this in hintr?  yeah, it should work and we should check that :)

params in the path - in hintr we're not sending these as like path?x=y but as path/<id> or so - we've got a test showing that is working already
to_json conversion - agree it should be tuneable, we should make a ticket for that
zip - Content-Disposition and a specific serializer, we have the serializer (just the binary type) but this sets the filename for the download via the Content-Disposition header - perhaps we could extend the pkgapi_returning_binary to accept an arg for the filename? See mrc-ide/hintr:R/endpoints.R@master#L491

2020-03-03 10:02 UTC, r-ash approved these changes
Looks great :)

2020-03-03 10:02 UTC, merged